---
# tasks file for docker-role
- name: "[INSTALL] - Update APT cache && upgrade APT to the latest packages"
  ansible.builtin.apt:
    update_cache: yes
    upgrade: yes
    cache_valid_time: 3600
  tags: update

- name: "[INSTALL] - Install necessary packages for Docker"
  ansible.builtin.apt:
    name: 
      - ca-certificates 
      - curl
      - gnupg
      - lsb-release
      - apt-transport-https
      - software-properties-common
      - python3-pip
      - virtualenv
      - python3-setuptools
    state: present
  tags: packages
  # update_cache: true

- name: "[INSTALL] - Add Docker's official GPG key"
  ansible.builtin.apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present
  tags: docker-install-gpg

- name: "[INSTALL] - Setting up the repository"
  ansible.builtin.apt_repository:
    # repo: deb https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable
    repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_lsb.codename }} stable
    state: present
  tags: setting-up-repo

- name: "[INSTALL] - Install Docker packages"
  ansible.builtin.apt:
    name: 
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-compose-plugin
    state: present
  tags: docker-packages

- name: "[INSTALL] - Add the user to the Docker group"
  user:
    name: "{{ ansible_user }}"
    groups: docker
    append: yes

- name: "[INSTALL] - Start the Docker daemon"
  service:
    name: docker
    state: started

- name: "[INSTALL] - Check if it is working by running a Hello World container"
  docker_container:
    name: hello-world-test
    image: hello-world
    state: started
  register: my-docker-hello-world

- name: display register
  debug:
    var: "{{ my-docker-hello-world }}"